### ISSUE TITLE
New command idea: Banana / where banana

### ISSUE THREAD

**Issue by kammt** [kammt/MemeAssembly#13]
Syntax  | Usage
------------- | -------------
banana | sets a jump marker
where banana | jumps to that jump marker

**Comment by xarantolus** [comment]
I like the idea of more ways to jump, especially using user-defined jump labels.

My suggestion would be the following:

```
monke uauaua             ; <- "uauaua" is set as a jump label in the code
...
return to monke uauaua   ; <- JMP uauaua
```

The jump labels after `monke` could be restricted so one can only use `u` and `a` in them (and must use both at least once)

This would allow creating many different jumps. The next interesting step would be adding different jumps (and a `cmp` before them), but I have no ideas for good names.

**Comment by kammt** [comment]
An idea for a cmp-jump I had was using the [who would win? meme](https://knowyourmeme.com/memes/who-would-win) for greater-jumps. An example could be
`who would win? v or v`

An Idea for the jump markers would then be `v wins`. That way however, I cannot set multiple jump markers for different comparison involving the same object.
For example: I want to jump to a specific location if eax is greater than 3 and just continue if that's not the case

```
who would win? eax or 3
3 wins
//continue with your normal code

eax wins
```
