### ISSUE TITLE
[Command suggestion] `[register] unlimited power [value/register]`

### ISSUE THREAD

**Issue by tomatoboyeet** [kammt/MemeAssembly#47]
**Command Syntax:** (e.g. `stonks [register]`) 
x unlimited power y
x^y

**Command Description:**
basic power operation on numbers.

Which x86_64 Assembly instruction(s) would be used to translate this command?
the words mason, what do they mean?

What could this command be useful for?
power

What Meme is your command based on? (You can also provide a link to e.g. its KnowYourMeme page)
unlimited power
https://knowyourmeme.com/memes/darth-sidious-unlimited-power

**Comment by tomatoboyeet** [comment]
i will be watching your career with great interest

**Comment by kammt** [comment]
I implemented this command in #50. I won't merge it now but will test it for a few days to make sure that I didn't do any mistakes like in #49. If you want to you can clone the branch to see if everything works for you.
The current implementation does not check for negative y-values, but I don't see that as a problem.

Thank you for your suggestion! 🚀

> i will be watching your career with great interest

<img width=10% src="https://i.redd.it/lxx7zbfww7341.jpg" alt="no u">
