### ISSUE TITLE
[Feature request] Add Windows support

### ISSUE THREAD

**Issue by tomatoboyeet** [kammt/MemeAssembly#53]
if you add windows, ide be able to code stuff, and ill donate as much as i can to this community.
ill do my best to do things like mixing code langs, but thats once i get windows version.
(thx bruh)
also, thx for adding the unlimited power, its kinda useful.

**Comment by kammt** [comment]
It's true that Windows-support might help this project get more attention. 
I've started working on this in the [feature/windows-support](https://github.com/kammt/MemeAssembly/tree/feature/windows-support) branch. The current main obstacle is that getline() is a POSIX-function and thus not available in Windows :/

Once that's out of the way, it'd be great if you could help testing it

**Comment by kammt** [comment]
In this state, it is possible to execute the binary under windows and display the help page.
But apart from that, compilation does not work - like at all. It seems to parse one line, not outputting any debug output after that and terminating after 1s without doing anything.

But there are some other problems. 
- By default, there is no Assembler in Windows' PATH-variable like there is GNU as on Linux. As far as I can see, the only real option is to install and use nasm, yet nasm and gnu as use a different syntax, which makes the currently generated Assembly code incompatible with nasm anyway. 
- The I/O commands use Linux syscalls, which are obviously not available on Windows. This means that these commands need a Windows-version

The only real solution I see is to create a second translation pattern for every command that uses the syntax that nasm wants and make nasm a requirement for MemeASM to work under Windows
If you or anyone else could help me out here, it'd be greatly appreciated

**Comment by xarantolus** [comment]
I think different translation patterns could work quite nicely. I just tried a bit with input/output on windows [here](https://github.com/xarantolus/winasm) and just using the predefined `printf`/`scanf` functions seems to work (no idea where they *are* actually defined though). Also not sure if the functions change any registers, they would of course need to be restored after the function call. Might however be nicer to use syscalls directly.

**Comment by kammt** [comment]
> But apart from that, compilation does not work - like at all. It seems to parse one line, not outputting any debug output after that and terminating after 1s without doing anything.

Turns out: On Windows, `strtok_r` is `strtok_s` and by replacing that, translation to Assembly works! 🥳 
Now while I was going through the pain of installing mingw64, I had a thought - couldn't we just use that as a requirement instead of NASM? After adding the bin-directory to your PATH-variable, you have access to gcc and also as, the GNU Assembler. This would mean that we only have to rewrite the I/O-commands and that's it (hopefully).


> and just using the predefined printf/scanf functions seems to work

That's a possibility, but it does feel a little like cheating to me :D. I'll research a bit more to see if we can get that to work without the C standard library.

> Also not sure if the functions change any registers

That's the fun part - Windows has its own ABI (because *why not* I guess)

**Comment by kammt** [comment]
So this is how far I have gotten until now when it comes to writechar:
```c
fprintf(outputFile,
                "\n\nwritechar:\n"
                "\tpush rcx\n"
                "\tpush rax\n"
                "\tpush rdx\n"
                "\tpush r8\n"
                "\tpush r9\n"
                //Get Handle of stdout
                "\tmov rcx, -11\n" //-11=stdout
                "\tcall GetStdHandle\n"//return value is in rax
                //Prepare the parameters for output
                "\tmov rcx, rax\n" //move Handle of stdout back into rcx
                "\tmov rdx, [rip + .LCharacter]\n"
                "\tmov r8, 1\n" //Length of message = 1 character
                "\tmov r9, [rip + .Ltmp64]\n" //Number of bytes written, just discard that value
                //Check if the stack is currently aligned. If so, we need to push twice to align it again (we need a NULL-value as the fifth parameter)
                "\ttest rsp, 0xFFFFFFFFFFFFFFFE\n"
                "\tjnz .LwcAlign\n"
                
                "\tpush 0\n"
                "\tcall WriteFile\n"
                "\tjmp .LwcRestore\n"
                
                "\t.LwcAlign:\n"
                "\tpush 0\n"
                "\tpush 0\n"
                "\tcall WriteFile\n"
                "\tadd rsp, 8\n"
                
                //Restore all registers
                "\t.LwcRestore:"
                "\tadd rsp, 8\n"
                "\tpop r9\n"
                "\tpop r8\n"
                "\tpop rdx\n"
                "\tpop rax\n"
                "\tpop rcx\n"
                "\tret\n");
```
The issue: WriteFile doesn't output anything and instead throws error `0x6` (ERROR_INVALID_HANDLE) and I have no clue why this happens (GetStdHandle works though, which makes this even more confusing)

**Comment by kammt** [comment]
> That's the fun part - Windows has its own ABI (because why not I guess)

That's also the reason why the code didn't work - I accidentally violated the Windows ABI.
Anyway, I/O-commands work now which means that all commands seem to work! :tada:

There's one issue: `-g` does not work within Windows, as STABS is not supported there (the Linker just throws a lot of errors when including STABS-information). The only real fix to that would be to add DWARF-support, which I'm currently not really interested in doing
