### ISSUE TITLE
the numbers mason, what do they mean? command

### ISSUE THREAD

**Issue by tomatoboyeet** [kammt/MemeAssembly#54]
**Command Syntax:** 
the numbers mason, what do they mean? <command>

**Command Description:** 
will serve as a "help" command, which will print the help manual of the command

What could this command be useful for? 
helping everyone trying this code lang.

What Meme is your command based on? 
https://knowyourmeme.com/forums/meme-research/topics/9811-the-numbers-masonwhat-do-they-mean
this meme is kinda dead, even very dead, but theres always someone to remember.

**Comment by kammt** [comment]
So this should print the usage of a command passed as a parameter? I don't see how this should be helpful in code, do you mean this as a console command?
Could you be a bit more specific?

>  helping everyone trying this code lang.

There is an explanation for every command at https://kammt.github.io/MemeAssembly/#/, but currently, memeasm's help page only outputs the GitHub-page. That could be changed.

**Comment by xarantolus** [comment]
If you install the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=xarantolus.memeassembly), you can actually just hover over any command to see what it does:

![Screenshot of a memeassembly file with a hover card in VSCode](https://user-images.githubusercontent.com/32465636/149669277-fab7aed8-5047-4fc3-b1c9-63cdf0e6325b.png)
