### ISSUE TITLE
[Bug] Not all return statements are accepted

### ISSUE THREAD

**Issue by xarantolus** [kammt/MemeAssembly#68]
**Describe the bug**
Some return statements do not appear to be interpreted as return statements when having multiple functions in a file.

**To Reproduce**
<details>
<summary>Code example or used MemeASM code</summary>

```
I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun a
    what can I say except a
    
    b: whomst has summoned the almighty one
    
    I see this as an absolute win

I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun b
    what can I say except b
    
    c: whomst has summoned the almighty one
    
    right back at ya, buckaroo



I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun c
    what can I say except c
    
    no, I don't think I will



I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun main
    
    a: whomst has summoned the almighty one
    
    
    I see this as an absolute win
```

</details>

Used compiler flags[e.g. -O-1 -c]: None, `memeasm -o './main' 'test.memeasm' && ./main`

**Debug Output**

<details>
<pre>
Opening file "test.memeasm" successful, parsing file...
The number of lines are 14
Struct array was created successfully
Parsing line: I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun a
        comparing with I
        comparing with like
        comparing with to
        comparing with have
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun
        comparing with {p}
                a contains a parameter
Parsing line:     what can I say except a
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
                Matching failed, attempting to match next command
        comparing with {p}:
                Matching failed - chars before or after {p} mismatching, attempting to match next command
        comparing with stonks
                Matching failed, attempting to match next command
        comparing with not
                Matching failed, attempting to match next command
        comparing with bitconneeeeeeect
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with \s
                Matching failed, attempting to match next command
        comparing with sneak
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with is
                Matching failed, attempting to match next command
        comparing with upvote
                Matching failed, attempting to match next command
        comparing with downvote
                Matching failed, attempting to match next command
        comparing with parry
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with units
                Matching failed, attempting to match next command
        comparing with upgrades,
                Matching failed, attempting to match next command
        comparing with they
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with is
                Matching failed, attempting to match next command
        comparing with look
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with UNLIMITED
                Matching failed, attempting to match next command
        comparing with upgrade
                Matching failed, attempting to match next command
        comparing with fuck
                Matching failed, attempting to match next command
        comparing with banana
                Matching failed, attempting to match next command
        comparing with where
                Matching failed, attempting to match next command
        comparing with monke
                Matching failed, attempting to match next command
        comparing with return
                Matching failed, attempting to match next command
        comparing with who
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with wins
                Matching failed, attempting to match next command
        comparing with corporate
                Matching failed, attempting to match next command
        comparing with they're
                Matching failed, attempting to match next command
        comparing with what
        comparing with can
        comparing with I
        comparing with say
        comparing with except
        comparing with {p}
                a contains a parameter
Parsing line:     b: whomst has summoned the almighty one
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
                Matching failed, attempting to match next command
        comparing with {p}:
                b: contains a parameter
        comparing with whomst
        comparing with has
        comparing with summoned
        comparing with the
        comparing with almighty
        comparing with one
Parsing line:     I see this as an absolute win
        comparing with I
        comparing with like
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
        comparing with see
        comparing with this
        comparing with as
        comparing with an
        comparing with absolute
        comparing with win
Parsing line: I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun b
        comparing with I
        comparing with like
        comparing with to
        comparing with have
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun
        comparing with {p}
                b contains a parameter
Parsing line:     what can I say except b
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
                Matching failed, attempting to match next command
        comparing with {p}:
                Matching failed - chars before or after {p} mismatching, attempting to match next command
        comparing with stonks
                Matching failed, attempting to match next command
        comparing with not
                Matching failed, attempting to match next command
        comparing with bitconneeeeeeect
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with \s
                Matching failed, attempting to match next command
        comparing with sneak
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with is
                Matching failed, attempting to match next command
        comparing with upvote
                Matching failed, attempting to match next command
        comparing with downvote
                Matching failed, attempting to match next command
        comparing with parry
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with units
                Matching failed, attempting to match next command
        comparing with upgrades,
                Matching failed, attempting to match next command
        comparing with they
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with is
                Matching failed, attempting to match next command
        comparing with look
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with UNLIMITED
                Matching failed, attempting to match next command
        comparing with upgrade
                Matching failed, attempting to match next command
        comparing with fuck
                Matching failed, attempting to match next command
        comparing with banana
                Matching failed, attempting to match next command
        comparing with where
                Matching failed, attempting to match next command
        comparing with monke
                Matching failed, attempting to match next command
        comparing with return
                Matching failed, attempting to match next command
        comparing with who
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with wins
                Matching failed, attempting to match next command
        comparing with corporate
                Matching failed, attempting to match next command
        comparing with they're
                Matching failed, attempting to match next command
        comparing with what
        comparing with can
        comparing with I
        comparing with say
        comparing with except
        comparing with {p}
                b contains a parameter
Parsing line:     c: whomst has summoned the almighty one
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
                Matching failed, attempting to match next command
        comparing with {p}:
                c: contains a parameter
        comparing with whomst
        comparing with has
        comparing with summoned
        comparing with the
        comparing with almighty
        comparing with one
Parsing line:     right back at ya, buckaroo
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
        comparing with back
        comparing with at
        comparing with ya,
        comparing with buckaroo
Parsing line: I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun c
        comparing with I
        comparing with like
        comparing with to
        comparing with have
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun
        comparing with {p}
                c contains a parameter
Parsing line:     what can I say except c
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
                Matching failed, attempting to match next command
        comparing with {p}:
                Matching failed - chars before or after {p} mismatching, attempting to match next command
        comparing with stonks
                Matching failed, attempting to match next command
        comparing with not
                Matching failed, attempting to match next command
        comparing with bitconneeeeeeect
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with \s
                Matching failed, attempting to match next command
        comparing with sneak
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with is
                Matching failed, attempting to match next command
        comparing with upvote
                Matching failed, attempting to match next command
        comparing with downvote
                Matching failed, attempting to match next command
        comparing with parry
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with units
                Matching failed, attempting to match next command
        comparing with upgrades,
                Matching failed, attempting to match next command
        comparing with they
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with is
                Matching failed, attempting to match next command
        comparing with look
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with UNLIMITED
                Matching failed, attempting to match next command
        comparing with upgrade
                Matching failed, attempting to match next command
        comparing with fuck
                Matching failed, attempting to match next command
        comparing with banana
                Matching failed, attempting to match next command
        comparing with where
                Matching failed, attempting to match next command
        comparing with monke
                Matching failed, attempting to match next command
        comparing with return
                Matching failed, attempting to match next command
        comparing with who
                Matching failed, attempting to match next command
        comparing with {p}
                what contains a parameter
        comparing with wins
                Matching failed, attempting to match next command
        comparing with corporate
                Matching failed, attempting to match next command
        comparing with they're
                Matching failed, attempting to match next command
        comparing with what
        comparing with can
        comparing with I
        comparing with say
        comparing with except
        comparing with {p}
                c contains a parameter
Parsing line:     no, I don't think I will
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
        comparing with I
        comparing with don't
        comparing with think
        comparing with I
        comparing with will
Parsing line: I like to have fun, fun, fun, fun, fun, fun, fun, fun, fun, fun main
        comparing with I
        comparing with like
        comparing with to
        comparing with have
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun,
        comparing with fun
        comparing with {p}
                main contains a parameter
Parsing line:     a: whomst has summoned the almighty one
        comparing with I
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
                Matching failed, attempting to match next command
        comparing with {p}:
                a: contains a parameter
        comparing with whomst
        comparing with has
        comparing with summoned
        comparing with the
        comparing with almighty
        comparing with one
Parsing line:     I see this as an absolute win
        comparing with I
        comparing with like
                Matching failed, attempting to match next command
        comparing with right
                Matching failed, attempting to match next command
        comparing with no,
                Matching failed, attempting to match next command
        comparing with I
        comparing with see
        comparing with this
        comparing with as
        comparing with an
        comparing with absolute
        comparing with win
Number of functions: 4
        Parsing function:
                Iteration stopped at index 4
        Parsing function:
test.memeasm:17: error: expected a return statement, but got a new function definition
                Iteration stopped at index 4
        Parsing function:
test.memeasm:24: error: expected a return statement, but got a new function definition
                Iteration stopped at index 3
        Parsing function:
                Iteration stopped at index 3
File parsing done, closing file...
Starting parameter validity check
        Checking parameter a
                Parameter is a valid function name
Starting parameter validity check
        Checking parameter a
                Parameter is not an 8 bit register
                Parameter is a character, translated to: 'a'
Starting parameter validity check
        Checking parameter b
                Parameter is a valid function name
Starting parameter validity check
Starting parameter validity check
        Checking parameter b
                Parameter is a valid function name
Starting parameter validity check
        Checking parameter b
                Parameter is not an 8 bit register
                Parameter is a character, translated to: 'b'
Starting parameter validity check
        Checking parameter c
                Parameter is a valid function name
Starting parameter validity check
Starting parameter validity check
        Checking parameter c
                Parameter is a valid function name
Starting parameter validity check
        Checking parameter c
                Parameter is not an 8 bit register
                Parameter is a character, translated to: 'c'
Starting parameter validity check
Starting parameter validity check
        Checking parameter main
                Parameter is a valid function name
Starting parameter validity check
        Checking parameter a
                Parameter is a valid function name
Starting parameter validity check
        Label duplicity check for function in line 1 in file 0
                Comparing against parameter b
                Comparing against parameter c
                Comparing against parameter main
        Label duplicity check for function in line 8 in file 0
                Comparing against parameter c
                Comparing against parameter main
        Label duplicity check for function in line 17 in file 0
                Comparing against parameter main
        Label duplicity check for function in line 24 in file 0
        Looking for function of parent command in line 4 in file 0
        Looking for function of parent command in line 11 in file 0
        Looking for function of parent command in line 26 in file 0
Starting jump label validity check for opcode 20
Starting jump label validity check for opcode 22
Beginning Monke jump label validity check
Starting analysis for "who would win?" command
Starting analysis for "corporate needs you to find the difference..." command
Chose random line for jump marker: 5
Starting analysis of the "Perfectly balanced..." command
        amount of times perfectly balanced was used: 0
        amount of lines to be deleted: 0
Analysis done, freeing memory
</pre></details>

**System Info (please complete the following information):**
 - Linux Distribution: WSL
 - GCC Version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
 - MemeASM Compiler Version: latest from develop branch
 - Installation method: Makefile (`sudo make install`)

**Comment by kammt** [comment]
Fixed with d13e5f1fcde59f095208c5b6a6d90adb794da908, thanks!
